=== struct-it/interbob/xsd/INTERBOB_glossary.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="urn:Glossary_V1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:Glossary="urn:Glossary_V1">
	<xs:complexType name="elementListType">
		<xs:sequence>
			<xs:element name="element" type="Glossary:elementType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="elementType">
		<xs:sequence>
			<xs:element name="usage" type="Glossary:elementUsageEnumType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="desc" type="xs:anyType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="parent" use="required" type="xs:string"/>
		<xs:attribute name="root" use="required" type="xs:string"/>
		<xs:attribute name="isEnum" use="optional" default="false" type="xs:boolean"/>
	</xs:complexType>
	<xs:element name="elements" type="Glossary:elementListType"/>
	<xs:simpleType name="elementUsageEnumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Conditionnel"/>
			<xs:enumeration value="Obligatoire"/>
			<xs:enumeration value="Obsolescent"/>
			<xs:enumeration value="Optionnel"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== struct-it/interbob/xsd/INTERBOB_glossary.xml
<?xml version="1.0" encoding="UTF-8"?>
<Glossary:elements xsi:schemaLocation="urn:Glossary_V1 INTERBOB_Glossary.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Glossary="urn:Glossary_V1">
	<!-- Entete XML -->
	<element name="xsi:schemaLocation" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Référence du schéma XML</desc>
	</element>	
	<!-- Entete des messages -->
	<element name="DateHeure" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Date-heure de l'extraction des données du message</desc>
	</element>
	<element name="CorrespondantEmetteur" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Caractéristiques du partenaire émetteur</desc>
	</element>
	<element name="Nom" parent="CorrespondantEmetteur" root="">
		<usage>Obsolescent</usage>
		<desc>Nom du partenaire émetteur</desc>
	</element>
	<element name="IdPartenaire" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Identifiant du partenaire</desc>
	</element>
	<element name="CodeBassin" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Code du bassin d'interopérabilité du partenaire</desc>
	</element>
	<element name="CodePays" parent="" root="">
		<usage>Conditionnel</usage>
		<desc>
			A utiliser obligatoirement si les échanges peuvent être réalisés dans un contexte 
			impliquant plusieurs pays.
		</desc>
	</element>
	<element name="CorrespondantDestinataire" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Caractéristiques du partenaire émetteur</desc>
	</element>
	<element name="Nom" parent="CorrespondantDestinataire" root="">
		<usage>Obsolescent</usage>
		<desc>Nom du partenaire destinataire</desc>
	</element>
	<element name="FormatMessage" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Propriétés du format de message</desc>
	</element>
	<element name="ReferenceNorme" parent="FormatMessage" root="">
		<usage>Obligatoire</usage>
		<desc>Type du message<br/>Forme IB:[type de message].</desc>
	</element>
	<element name="VersionNorme" parent="FormatMessage" root="">
		<usage>Obligatoire</usage>
		<desc>
			Concaténation de 2 éléments : 
			<ul>
			<li>en majeur la version InterBOB suivie du séparateur ":"</li>
			<li>lui-même suivi d'un identifiant optionnel (mais conseillé) de version d'implémentation et à définir entre les partenaires impliqués dans les échanges.</li>
			</ul>
			Exemple : 1.0:8.5.<br/>
			La numérotation des versions d'implémentation (8.5 dans l'exemple) est gérée par le CERTU.
		</desc>
	</element>
	<element name="IdMessage" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>
			Cette donnée doit permettre (seule ou avec d'autres informations) d'identifier le message, 
			d'effectuer la traçabilité et éventuellement de contrôler des pertes de séquence,
			selon les règles édictées au niveau du bassin.<br/>
			Doit être égale au numéro séquentiel attribué au message (dépend de l’émetteur):<br/>
			<ul>
			<li>Limite basse = 1</li>
			<li>Limite haute = 65535</li> 
			<li>Retour à 1 lorsque la limite haute est atteinte</li>
			</ul>
		</desc>
	</element>
	<!-- IBLSLN -->
	<element name="IBLSLN:MajListeSecurite" parent="" root="">
		<desc>Demande d'interdiction d’une application transport ou d'un billet sans contact, 
			qui sera placé dans une liste d'interdiction de titres de transport</desc>
	</element>
	<element name="ListeSecurite" parent="IBLSLN:MajListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Liste d'applications transport ou de Billet Sans Contact à invalider</desc>
	</element>
	<element name="DateHeureEmission" parent="ListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Date et heure d'émission de la liste</desc>
	</element>
	<element name="TypeListeSecurite" parent="ListeSecurite" root="IBLSLN:MajListeSecurite" isEnum="true">
		<usage>Obligatoire</usage>
		<desc>Type de la liste<br/>Doit être égal à "2:Liste d'interdictions"</desc>
	</element>
	<element name="ActionParDefaut" parent="ListeSecurite" root="" isEnum="true">
		<usage>Conditionnel</usage>
		<desc>Permet de définir la valeur par défaut de l'action à réaliser sur les entrées de la liste
				dont l'élément "ActionDemandee" n'est pas présent.<br/>
				Si présent, peut prendre les valeurs suivantes :
				<ul>
				<li>"4":Invalider = Rendre inutilisable (mais peut toujours être lu)</li>
				<li>"7":Aucune opération d’invalidation demandée</li>
				</ul>
			</desc>
	</element>
	<element name="TypeMiseaJour" parent="ListeSecurite" root="IBLSLN:MajListeSecurite" isEnum="true">
		<usage>Obsolescent</usage>
		<desc>Permet de préciser si: 
				<ul>
				<li>c'est une liste exhaustive qui est transmise : "1"</li>
				<li>ce ne sont que des mises à jour (« incrémentiel ») : "2".</li>
				</ul>
				Dans le cas d'un message IBLSLN, c'est la liste exhaustive qui est transmise.
		</desc>
	</element>
	<element name="EntreeListeSecurite" parent="ListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Entrée de la liste</desc>
	</element>
	<element name="EntreeApplicationInstallee" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Entrée de la liste de type "Application Installée"</desc>
	</element>
	<element name="ActionDemandee" parent="EntreeApplicationInstallee" root="IBLSLN:MajListeSecurite" isEnum="true">
		<usage>Conditionnel</usage>
		<desc>Permet de définir la valeur de l'action à réaliser lors de la détection de l'objet.<br/>
			Cette valeur est à préciser en local par les partenaires du bassin d'interopérabilité.<br/>
			Les valeurs reprennent l'énumération de l'élément ActionParDefaut.
		</desc>
	</element>
	<element name="DateDebutEffet" parent="EntreeApplicationInstallee" root="IBLSLN:MajListeSecurite">
		<usage>Conditionnel</usage>
		<desc>Date d’entrée effective en liste d’opposition.<br/>
			Si la date est absente au niveau de l'élément on considère que l’échéance d’effet est : 
			dès que possible
		</desc>
	</element>
	<element name="ApplicationInstallee" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Caractéristiques de l'application transport ou du Billet Sans Contact</desc>
	</element>
	<element name="AID" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Identification de l’application.<br/>
			99-502 pour le transport. Autres référentiels sinon.
		</desc>
	</element>
	<element name="IdApplicationInstallee" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Numéro de série de l'application</desc>
	</element>
	<element name="MatriceApplicationEnregistree" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Propriétés de la matrice application</desc>
	</element>
	<element name="BassinsAcceptation" parent="MatriceApplicationEnregistree" root="">
		<usage>Obligatoire</usage>
		<desc>Liste des réseaux sur lesquels la matrice application est acceptée</desc>
	</element>
	<element name="FormeContenant" parent="" root="" isEnum="true">
		<usage>Obligatoire</usage>
		<desc>Permet d’identifier la forme physique du contenant de l’application transport : 
			carte, billet, carte SIM, carte SD, clé USB, …
		</desc>
	</element>
	<element name="StructureApplication" parent="" root="" isEnum="true">
		<usage>Obligatoire</usage>
		<desc>Structure de l’application : GTML, Tango, CD97-2, Triangle n, …</desc>
	</element>
	<element name="Distributeur" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Identification du partenaire émetteur de l’application</desc>
	</element>
	<element name="DateHeureFinValidite" parent="ApplicationInstallee" root="">
		<usage>Conditionnel</usage>
		<desc>Date de fin de validité de l’application<br/>
			Si l’exploitant a l’information, il la transmet obligatoirement.</desc>
	</element>
	<element name="Support" parent="ApplicationInstallee" root="">
		<usage>Conditionnel</usage>
		<desc>Correspond au support sur lequel l'application est installée.<br/>
			A utiliser obligatoirement si l'élément IdSupport est différent 
			de l'élément AID, ou bien si le support n’a pas d’application.
		</desc>
	</element>
	<element name="TypeSupport" parent="Support" root="" isEnum="true">
		<usage>Obsolescent</usage>
		<desc>Type de support sur lequel l’opération est réalisée.</desc>
	</element>
	<element name="IdSupport" parent="Support" root="">
		<usage>Obligatoire</usage>
		<desc>Numéro de série du support.</desc>
	</element>
	<!-- IBCS__ -->
	<element name="IBCS:CompteRenduSecurite" parent="" root="">
		<desc>Compte-rendu de l’invalidation par un équipement d’une application transport ou 
			d'un billet sans contact qui était placé dans la liste d’interdiction</desc>
	</element>
	<element name="ActionListeSecurite" parent="" root="">
		<usage>Obligatoire</usage>
		<desc>Liste des actions effectuées dans la liste</desc>
	</element>
	<element name="DateHeureAction" parent="ActionListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Date et heure de génération de liste</desc>
	</element>
	<element name="TypeListeSecurite" parent="ActionListeSecurite" root="" isEnum="true">
		<usage>Obligatoire</usage>
		<desc>Type de liste</desc>
	</element>
	<element name="LieuAction" parent="ActionListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Lieu géographique pour lequel la liste a été générée</desc>
	</element>
	<element name="IdLocalisation" parent="LieuAction" root="">
		<usage>Obligatoire</usage>
		<desc>Identifiant du lieu</desc>
	</element>
	<element name="ReferentielLocalisation" parent="LieuAction" root="">
		<usage>Obligatoire</usage>
		<desc>Identifiant du référentiel géographique associé au lieu</desc>
	</element>
	<element name="EquipementAction" parent="ActionListeSecurite" root="">
		<usage>Obligatoire</usage>
		<desc>Equipement pour lequel la liste a été générée</desc>
	</element>
	<element name="IdEquipement" parent="EquipementAction" root="">
		<usage>Obligatoire</usage>
		<desc>Identifiant de l'équipement</desc>
	</element>
	<element name="Referentiel" parent="EquipementAction" root="">
		<usage>Obligatoire</usage>
		<desc>Identifiant du référentiel géographique associé à l'équipement</desc>
	</element>
